on:
  push:
    branches: ["master"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p pages
          cp iliazeus.db.tar pages/iliazeus.db
          cp iliazeus.files.tar pages/iliazeus.files
          cp */*.pkg.* pages
      - uses: actions/upload-pages-artifact@v3
        with: { path: pages }
      - uses: actions/deploy-pages@v4
        id: deployment
